
obj-$(CONFIG_FUELGAUGE_MAX77729)	+= max77729_fuelgauge.o
obj-$(CONFIG_CHARGER_MAX77729)	+= max77729_charger.o

ccflags-y += -Wformat $(DISABLE_LTO_CLANG) $(DISABLE_CFI_CLANG) -fno-data-sections -fno-function-sections
